# Generated by Django 3.2 on 2023-04-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
